### ISSUE TITLE
Add CI support and badge

### ISSUE THREAD

**Issue by gorangajic** [benoror/better-npm-run#32]
@benoror we already have some tests, why don't add some CI support ?

I use [semaphoreci.com](https://semaphoreci.com/) for my open source project because it's free and things just work out of the box, but you can use whatever you want

**Comment by benoror** [comment]
@gorangajic yeah that should probably be a good idea, since it's getting some traction and many projects now depend on this.

Unfortunately I don't have much spare time atm. Nevertheless I'm open to PRs and proposals if you'd like to work on this. :)

Already added you as collaborator :tada: :smile:

**Comment by gorangajic** [comment]
Thanks, but I can't add CI support because it's not possible to do that as collaborator.
nvm it's not urgent whenever you can

**Comment by benoror** [comment]
@gorangajic just added you as contributor on semaphoreci.com :smile: thanks for the suggestion!
