### ISSUE TITLE
overwrite .env from package.json

### ISSUE THREAD

**Issue by maticrivo** [benoror/better-npm-run#41]
Lets say i have a `.env` like follows:
```
FOO=bar
```

and a `package.json` file like follows:
```
{
  ...
  "scripts": {
    "start": "better-npm-run start"
  },
  "betterScripts": {
    "start": {
      "ENV": {
        "FOO": "tar"
      },
      "command": "node index.js"
    }
  },
  ...
}
```

and `index.js` looks like this:
```
console.log("FOO:", process.env.FOO);
```

i would expect the value of FOO to be the one in `package.json` and not the one in `.env`.
i would expect the output to be `FOO: tar` but instead im getting `FOO: bar`

any idea what im doing wrong?

**Comment by benoror** [comment]
Hi @maticrivo!

dot-env package (https://www.npmjs.com/package/dotenv) will replace during runtime anything you have in your Environment previous to execution:
https://github.com/benoror/better-npm-run/blob/master/lib/exec.js#L1

including better-npm-run's env:
https://github.com/benoror/better-npm-run/blob/master/lib/exec.js#L11

I would say this is the expected behaviour, otherwise what's the point of placing an `.env.` file in the firstplace?

Nevertheless I'm open for discussion, and as always you can [submit a PR](http://makeapullrequest.com/) with **proper test(s) and proposed changes** 😄

**Comment by maticrivo** [comment]
Hi @benoror 
Thanks for the quick response. I wasn't aware of that information about dot-env package.

If i think of something i'll re open this issue with a proper PR.
