### ISSUE TITLE
Docs Question: what is `$npm_package_webpack`?

### ISSUE THREAD

**Issue by dtothefp** [benoror/better-npm-run#9]
I exectued:

```json
  "scripts": {
    "watch": "better-npm-run watch",
  },
  "betterScripts": {
    "watch": {
      "command": "echo $npm_package_webpack",
      "env": {
        "NODE_ENV": "development"
      }
    },
```
```
npm run watch
```
<img width="613" alt="screen shot 2015-10-21 at 11 40 53 am" src="https://cloud.githubusercontent.com/assets/4656726/10641760/9deac3a8-77e8-11e5-9693-0a7f7809828a.png">

Not sure if there is a use case for `$npm_package_webpack`, seems confusing in the docs

**Comment by benoror** [comment]
I'm not completely sure what are you talking about, but from what I see you might want to run `npm run watch`.

Gonna close this if no further questions.

**Comment by dtothefp** [comment]
What exactly is `$npm_package_webpack`? Is that an environmental variable supplied by NPM or just some sort of shorthand in your docs. 

Also when using eslint with this package it swallows all the output colors. From what I've read it's not possible to output colors with `child_process.exec` only `spawn`.  Is there something I'm missing?

**Comment by benoror** [comment]
Ohh, now I understand. I borrowed the example script from angular-formly project, since better-npm-run was originally created for it: https://github.com/formly-js/angular-formly/pull/350/files . So my guess is that `$npm_package_webpack` was some sort of Env variable used by it, you can ignore it.

Regarding the output colors I am aware of it, you might wat to submit a PR (using `spawn` :smile:) or [try this other](https://github.com/benoror/better-npm-run/issues/10) alternatives:

- https://github.com/kentcdodds/argv-set-env
- https://github.com/kentcdodds/cross-env (uses `spawn`)

**Comment by Anenth** [comment]
`$npm_package_webpack` might be a config value. 
We can create new variables in package.json using `config`
eg.
``` 
"config": {
  "js": "my_box/src/js/"
}
```
This can be called inside the script 
```
"scripts": {
  "lint": "eslint $npm_package_config_js",
}
```
